# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(10, 0, 771, 461))
        self.photo.setText("")
        self.photo.mousePressEvent = self.printSomething
        self.photo.setPixmap(QtGui.QPixmap("Tutorials\\photos\\1.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.cat = QtWidgets.QPushButton(self.centralwidget)
        self.cat.setGeometry(QtCore.QRect(10, 460, 321, 51))
        self.cat.setObjectName("cat")
        self.cat.clicked.connect(self.show_veverita)
        
        self.vulpe = QtWidgets.QPushButton(self.centralwidget)
        self.vulpe.setGeometry(QtCore.QRect(470, 460, 311, 51))
        self.vulpe.setObjectName("vulpe")
        self.vulpe.clicked.connect(self.show_vulpe)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def printSomething(self,event):
        print("Hello")
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cat.setText(_translate("MainWindow", "Veveriță"))
        self.vulpe.setText(_translate("MainWindow", "vulpe"))
    def show_veverita(self):
        self.photo.setPixmap(QtGui.QPixmap("Tutorials\\photos\\1.jpg"))
    def show_vulpe(self):
        self.photo.setPixmap(QtGui.QPixmap("Tutorials\\photos\\2.jpeg"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
